<template>
	<div>

		<v-toolbar app color="primary" dark>
			<v-btn icon @click="backToMain">
				<v-icon>arrow_back</v-icon>
			</v-btn>
			<!-- <v-btn icon @click="editProfile">
				<v-icon>border_color</v-icon>
			</v-btn> -->
			<v-spacer></v-spacer>
			<ContactsBadge/>
			<Accounts />
		</v-toolbar>

		<v-container fluid grid-list-lg>
			<v-layout row fill-height>
				<v-flex xs6>
					<div class="text-xs-center">
						<v-avatar size="90px" class="elevation-5" tile>
							<v-img
								v-if="user.downloadURL"
								width="90"
								:src="user.downloadURL"
								alt="avatar"
								contain
							></v-img>
							<v-img
								v-else
								width="90"
								:src="user.imageObj.src"
								alt="avatar"
								contain
							></v-img>
							<v-img
								contain
								:src="require('./../../static/img/camera-icon.png')"
								class="overlayImage"
								width="30"
								@click="sheet = true"
								v-if="!loading"
							></v-img>
							<v-progress-circular v-else color="primary lighten-2" class="overlayImage" indeterminate></v-progress-circular>
						</v-avatar>
					</div>
					<br />
				</v-flex>
				<ProfileHeader :hasViewProfile="false" :hasRating="false" :displayProfilePicture="false" />
			</v-layout>
			<v-bottom-sheet full-width v-model="sheet">
				<v-list>
					<v-subheader v-if="!user.downloadURL">Add using</v-subheader>
					<v-subheader v-else>Update using</v-subheader>
					<v-list-tile @click="takePicture('camera')">
						<v-list-tile-avatar>
							<v-icon>camera_alt</v-icon>
						</v-list-tile-avatar>
						<v-list-tile-title>Camera</v-list-tile-title>
					</v-list-tile>
					<v-list-tile @click="takePicture('photo_library')">
						<v-list-tile-avatar>
							<v-icon>photo_library</v-icon>
						</v-list-tile-avatar>
						<v-list-tile-title>Gallery</v-list-tile-title>
					</v-list-tile>
				</v-list>
			</v-bottom-sheet>
			<div :class="[user.type === 'Customer' ? 'mt-3' : 'mt-4']">
				<v-layout row wrap>
					<v-flex xs4>
						<p class="grey--text header-text" v-if="user.type === 'Reseller'">Branch ID</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.type === 'Reseller'">{{user.agentId}}</p>
					</v-flex>
					<!-- <v-flex xs4>
						<p class="grey--text header-text">Branch Name</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.branchName || 'Your Branch Name'}}</p>
					</v-flex> -->
					<v-flex xs4>
						<p class="grey--text header-text">Branch Manager</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.firstName}} {{user.middleInitial}} {{user.lastName}}</p>
					</v-flex>
					<!-- <v-flex xs4>
						<p class="grey--text header-text">Birthday</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.birthday | birthdayFormat}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Gender</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.gender}}</p>
					</v-flex> -->
					<v-flex xs4 v-if="!user.isEmailAutogenerated">
						<p class="grey--text header-text">Email</p>
					</v-flex>
					<v-flex xs8 v-if="!user.isEmailAutogenerated">
						<p class="body-1 header-text grey--text text--darken-2">{{user.email}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Contact</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.contact}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Lot Number / Bldg.</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.house">{{user.address.house}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Street name</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.streetName">{{user.address.streetName}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Province</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.province">{{user.address.province}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">City/Municipality</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.citymun">{{user.address.citymun}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Barangay</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.barangay">{{user.address.barangay}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Zip Code</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.zipCode">{{user.address.zipCode}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Facebook</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.social && user.social.facebook">{{user.social.facebook}}</p>
					</v-flex>
					<!--<v-flex xs4>
						<p class="grey--text header-text">Instagram</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.instagram && user.social.instagram">{{user.social.instagram}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Twitter</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.social && user.social.twitter">{{user.address.twitter}}</p>
					</v-flex>-->
				</v-layout>
			</div>
		</v-container>

		<BottomNav currentTab="more"/>
	</div>
</template>

<script>
import {mapGetters} from 'vuex';
import moment from 'moment';
import ProfileHeader from '@/components/ProfileHeader';
import ContactsBadge from '@/components/ContactsBadge';
import {mixins} from '@/mixins';

export default {
	mixins: [mixins],
	components: {
		ProfileHeader, ContactsBadge
	},

	data: () => ({
		userData: {},
		sheet: false,
		loading: false,
	}),

	created() {
		console.log("userData:", this.userData);
		console.log("user:", this.user);

		this.userData = Object.assign({}, this.userData, this.user);
	},
		
	computed: {
		...mapGetters({
			user: "accounts/user"
		})
	},

	methods: {
		backToMain() {
			this.$router.go(-1);
		},
		editProfile () {
			this.$router.push({name: 'EditProfile'})
		},
		takePicture(selected) {
			this.loading = true;
			this.$store
				.dispatch("plugins/TAKE_PHOTO_FOR_REGISTRATION", selected)
				.then(res => {
					this.sheet = false;
					if (res) {
						this.$store
							.dispatch("accounts/UPDATE_PROFILE_PHOTO", res)
							.then(() => {
								this.createFakeImage(res).then(data => {
								this.profileImage = {
									height: data.height + "px",
									width: data.width + "px"
								};
								this.loading = false;
							});
						})
						.catch(e => {
							console.error(e);
							this.loading = false;
						});
					}
				})
				.catch(error => {
					this.sheet = false;
					this.loading = false;
					alert(error);
				});
		}
	},

	filters: {
		birthdayFormat (val) {
			return moment(val).format('MMMM DD, YYYY')
		}
	}
}

</script>

<style scoped>
.header-text {
  font-size: 11px;
}
.overlayImage {
  position: absolute;
  z-index: 1;
}
</style>

