<template>
  <div>
    <v-toolbar app color="primary" dark>
      <BasketBadge />
      <v-spacer></v-spacer>
      <Accounts />
    </v-toolbar>

    <v-container fluid grid-list-lg v-if="user.type === 'Reseller'">
      <ProfileHeader :hasRating="false" />
      <div v-if="user.referredBy">
        <v-list two-line class="transparent mt-3" dense>
          <v-list-tile avatar ripple @click="viewReseller">
            <v-list-tile-avatar>
              <v-avatar v-if="user.referredBy.downloadURL" width="50px">
                <v-img
                  :src="user.referredBy.downloadURL"
                  width="50"
                  contain
                ></v-img>
              </v-avatar>
              <v-avatar v-else width="50px">
                <v-img :src="MaleDefaultImage" width="50" contain></v-img>
              </v-avatar>
            </v-list-tile-avatar>
            <v-list-tile-content>
              <v-list-tile-sub-title>Referred By:</v-list-tile-sub-title>
              <v-list-tile-title class="grey--text text--darken-2"
                >{{ user.referredBy.firstName }}
                {{ user.referredBy.middleInitial }}
                {{ user.referredBy.lastName }}</v-list-tile-title
              >
            </v-list-tile-content>
          </v-list-tile>
        </v-list>
      </div>
      <div v-else class="mt-3">
        No Referred By...
        <a
          style="text-decoration: none;"
          @click="
            $router.push({ name: 'EditReseller', params: { action: 'add' } })
          "
          >Add one?</a
        >
      </div>
    </v-container>
    <v-container fluid grid-list-lg v-else-if="user.type === 'Customer'">
      <ProfileHeader />
      <div v-if="!user.resellerId" class="mt-2">
        No reseller yet.
        <a
          style="text-decoration: none;"
          @click="
            $router.push({ name: 'EditReseller', params: { action: 'add' } })
          "
          >Add one?</a
        >
      </div>
      <div v-else>
        <v-list two-line class="transparent" dense>
          <v-list-tile avatar ripple @click="viewReseller">
            <v-list-tile-avatar>
              <v-avatar v-if="user.resellerData.downloadURL" width="50px">
                <v-img
                  :src="user.resellerData.downloadURL"
                  width="50"
                  contain
                ></v-img>
              </v-avatar>
              <v-avatar v-else width="50px">
                <v-img :src="MaleDefaultImage" width="50" contain></v-img>
              </v-avatar>
            </v-list-tile-avatar>
            <v-list-tile-content>
              <v-list-tile-sub-title>Your Reseller</v-list-tile-sub-title>
              <v-list-tile-title class="grey--text text--darken-2"
                >{{ user.resellerData.firstName }}
                {{ user.resellerData.middleInitial }}
                {{ user.resellerData.lastName }}</v-list-tile-title
              >
            </v-list-tile-content>
          </v-list-tile>
        </v-list>
        <v-dialog v-model="viewResellerData">
          <v-card>
            <v-container fluid grid-list-md>
              <div class="title grey--text text--darken-3 mb-3 text-xs-center">
                Agent ID {{ resellerData.agentId }}
              </div>
              <v-layout row wrap>
                <v-flex xs4>
                  <v-avatar v-if="resellerData.downloadURL" width="92px" tile>
                    <v-img :src="resellerData.downloadURL"></v-img>
                  </v-avatar>
                  <v-avatar v-else width="92px" tile>
                    <v-img :src="resellerData.placeholder"></v-img>
                  </v-avatar>
                </v-flex>
                <v-flex xs8>
                  <div class="body-2 mb-1 grey--text text--darken-3">
                    {{ resellerData.firstName }}
                    {{ resellerData.middleInitial }}
                    {{ resellerData.lastName }}
                  </div>
                  <p
                    class="grey--text"
                    v-if="!resellerData.isEmailAutogenerated"
                  >
                    <v-icon color="grey">mail</v-icon>
                    {{ resellerData.email }}
                  </p>
                  <p class="grey--text">
                    <v-icon color="grey">phone</v-icon>
                    {{ resellerData.contact }}
                  </p>
                  <p class="grey--text">
                    Member since {{ resellerData.createdAt | memberSince }}
                  </p>
                </v-flex>
              </v-layout>
            </v-container>
          </v-card>
        </v-dialog>
      </div>
    </v-container>

    <div
      class="px-3"
      v-if="user.type === 'Reseller' && user.status === 'pending'"
    >
      <v-alert border="right" outline color="info" value="true" elevation="2">
        Hello! Your Reseller application is currently pending for review.<br /><br />
        Check back to this page to see if your application has been approved, or
        you can contact the Avon Team on Viber at 09123456789.
      </v-alert>
    </div>

    <div
      class="px-3"
      v-else-if="user.type === 'Reseller' && user.status === 'denied'"
    >
      <v-alert border="right" outline type="error" value="true" elevation="2">
        Application was denied due to: {{ user.remarks }}
      </v-alert>
    </div>

    <div
      class="text-xs-center"
      v-if="user.type === 'Reseller' && user.status === 'denied'"
    >
      <v-btn
        depressed
        class="primary white--text"
        @click="ResubmitApplication"
        :loading="loading"
        :disabled="loading"
      >
        Resubmit Application <v-icon right>send</v-icon>
      </v-btn>
    </div>

    <v-list class="transparent">
      <v-list-tile
        avatar
        v-for="item in listByUserType"
        :key="item.name"
        @click="option(item.name)"
        ripple
      >
        <v-list-tile-action>
          <v-icon color="grey darken-1" v-text="item.icon"></v-icon>
        </v-list-tile-action>
        <v-list-tile-content>
          <v-list-tile-title
            class="grey--text text--darken-1"
            v-text="item.name"
          ></v-list-tile-title>
        </v-list-tile-content>
        <v-list-tile-action>
          <v-icon color="grey darken-1">keyboard_arrow_right</v-icon>
        </v-list-tile-action>
      </v-list-tile>
    </v-list>

    <TermsAndConditionsDialog ref="TermsAndConditionsDialog" />
    <DataPolicy ref="DataPolicy" />

    <BottomNav currentTab="more" />
    <Modal ref="modal" />

    <div>
      <v-dialog v-model="logoutDialog" persistent>
        <v-card>
          <v-card-title class="subheading font-weight-bold primary white--text"
            >CONFIRMATION</v-card-title
          >
          <v-divider />
          <v-card-text>Are you sure you want to log out?</v-card-text>
          <v-card-actions>
            <v-spacer />
            <v-btn @click="logoutDialog = false">CANCEL</v-btn>
            <v-btn color="primary" @click="logoutUser">LOG-OUT</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </div>
  </div>
</template>



<script>
import { mapGetters } from "vuex";
import { mixins } from "@/mixins";
import moment from "moment";
import ProfileHeader from "@/components/ProfileHeader";
import BasketBadge from "@/components/BasketBadge";
import Modal from "@/components/Modal";
import TermsAndConditionsDialog from "@/components/TermsAndConditionsDialog";
import DataPolicy from "@/components/DataPolicy";
import MaleDefaultImage from "@/assets/img/male-default.jpg";

export default {
  data: () => ({
    list: [
      {
        icon: "settings",
        name: "Settings",
        type: "Reseller",
        both: true
      },
      {
        icon: "help",
        name: "Support",
        type: "Reseller",
        both: true
      },
      {
        icon: "lock",
        name: "Data Privacy Policy",
        type: "Reseller",
        both: true
      },
      {
        icon: "format_list_bulleted",
        name: "Terms & Conditions",
        type: "Reseller",
        both: true
      },
      {
        icon: "exit_to_app",
        name: "Log out",
        type: "Reseller",
        both: true
      }
    ],
    viewResellerData: false,
    resellerData: {},
    loading: false,
    MaleDefaultImage: MaleDefaultImage,
    logoutDialog: false
  }),
  methods: {
    logoutUser() {
      this.Indicator().open();
      this.$store.dispatch("accounts/LOG_OUT").then(() => {
        this.Indicator().close();
        this.$router.push({ name: "Home" });
      });
    },
    option(name) {
      if (name !== "Log out" && this.user.status === "pending") {
        this.$refs.modal.show(
          "Sorry",
          "Your application is under review - please check this page regularly to see if it has been approved."
        );
        return;
      }

      if (name === "Log out") {
        this.logoutDialog = true;
      } else if (name === "Settings") {
        this.$router.push({ name: "Settings" });
      } else if (name === "Contacts") {
        this.$router.push({ name: "Contacts" });
      } else if (name === "Support") {
        this.$router.push({ name: "Support" });
      } else if (name === "Data Privacy Policy") {
        this.$refs.DataPolicy.show();
      } else if (name === "Terms & Conditions") {
        this.$refs.TermsAndConditionsDialog.show();
      }
    },

    viewReseller() {
      if (this.user.type === "Reseller") {
        this.resellerData = Object.assign({}, this.user.referredBy);
        console.log(this.resellerData);
      } else {
        this.resellerData = Object.assign({}, this.user.resellerData);
      }

      this.viewResellerData = true;
    },

    goToMSA() {
      this.$router.push({ name: "MySellingAssistant" });
    },

    async ResubmitApplication() {
      // this.loading = true;
      // try {
      //   await this.$store.dispatch("accounts/RESUBMIT_STATUS");
      // } catch (error) {
      //   console.log(error);
      // }
      // this.loading = false;
      this.$router.push({ name: "EditProfile" });
    }
  },
  computed: {
    ...mapGetters("accounts", ["user"]),
    listByUserType() {
      return this.list.filter(l => l.type === this.user.type || l.both);
    }
  },
  filters: {
    memberSince(val) {
      return moment(val).format("MMMM D");
    }
  },
  components: {
    ProfileHeader,
    BasketBadge,
    Modal,
    TermsAndConditionsDialog,
    DataPolicy
  },
  mixins: [mixins]
};
</script>

<style scoped>
.star-icon {
  font-size: 18px;
}

.flipped {
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
}
</style>
