module.exports = {
  NODE_ENV: '"production"',
  projectId: '"pickupsticks-dev"',
  appId: '"1:6834088913:web:fce7c161cf1ed751da8ef0"',
  databaseURL: '"https://pickupsticks-dev.firebaseio.com"',
  storageBucket: '"pickupsticks-dev.appspot.com"',
  apiKey: '"AIzaSyDIzeMplcaHQoy0bl3revSAoLX_5o3LmTU"',
  authDomain: '"pickupsticks-dev.firebaseapp.com"',
  messagingSenderId: '"6834088913"',
  webAdminId: '"admin"',
  companyName: '"Pick Up Sticks"',
  contactNumber: '"09123456789"',
  version: '"0.6.10"',
  primaryColor: '"#f78e20"',
  environment: '"live"',
  callbackURL: '"https://us-central1-pickupsticks-dev.cloudfunctions.net/callback/checkPaymentStatus"',
}
