module.exports = {
  NODE_ENV: '"production"',
  apiKey: '""',
  authDomain: '""',
  databaseURL: '""',
  projectId: '""',
  storageBucket: '""',
  messagingSenderId: '""',
  appId: '""',
  storageCode: '""',
  webAdminId: '"admin"',
  companyName: '"Mother Nurture"',
  version: '"0.6.8"',
  primaryColor: '"#90b252"',
  environment: '"live"',
  callbackURL: '""',
}
