<template>
	<div>

		<v-toolbar app color="primary" dark>
			<v-btn icon @click="backToContacts">
				<v-icon>arrow_back</v-icon>
			</v-btn>

			<v-btn icon @click="$router.push({name: 'EditOfflineContact', params: {data: user}})" v-if="user.isOffline">
				<v-icon>mode_edit</v-icon>
			</v-btn>

			<v-spacer></v-spacer>
			<Logo />
		</v-toolbar>

		<v-container fluid grid-list-lg>
			<v-layout row wrap>
				<v-flex xs4>
					<!-- <v-avatar :tile="true" size="92px" class="grey lighten-4">
						<img v-lazy="user.imageObj" class="mt-2 elevation-1 flipped" alt="avatar">
					</v-avatar> -->
					<img v-lazy="user.imageObj" class="mt-2 elevation-1 flipped" alt="avatar" :style="profileImage">
				</v-flex>
				<v-flex xs8>
					<div class="headline mb-1">
						{{user.firstName}} {{user.middleInitial}} {{user.lastName}}
					</div>
					<div class="grey--text">Member since {{user.createdAt | memberSince}}</div>
				</v-flex>
			</v-layout>
			<div :class="[user.type === 'Customer' ? 'mt-3' : 'mt-4']">
				<v-layout row wrap>
					<v-flex xs4>
						<p class="grey--text header-text">Name</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.firstName}} {{user.middleInitial}} {{user.lastName}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Birthday</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.birthday | birthdayFormat}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Gender</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.gender}}</p>
					</v-flex>
					<v-flex xs4 v-if="!user.isEmailAutogenerated">
						<p class="grey--text header-text">Email</p>
					</v-flex>
					<v-flex xs8 v-if="!user.isEmailAutogenerated">
						<p class="body-1 header-text grey--text text--darken-2">{{user.email}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Contact</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.contact}}</p>
					</v-flex>
				</v-layout>
			</div>
			<div class="text-xs-center pb-1" v-if="user.isOffline">
				<v-btn large color="primary" dark @click="viewBasket">
					<v-icon left>shopping_cart</v-icon> View Cart
				</v-btn>
			</div>
		</v-container>

		<v-dialog v-model="confirmationDialog" persistent>
			<v-card>
				<v-card-title>
					<div class="headline">Confirmation</div>
				</v-card-title>
				<v-card-text>
					Are you sure you want to delete this contact?
				</v-card-text>
				<v-card-actions>
					<v-spacer></v-spacer>
					<v-btn color="grey darken-2" flat @click="confirmationDialog = false">Cancel</v-btn>
					<v-btn color="red" flat @click="deleteContact">Yes</v-btn>
				</v-card-actions>
			</v-card>
		</v-dialog>

	</div>
</template>

<script>
import {
	mapGetters
} from 'vuex'
import moment from 'moment'
import {mixins} from '@/mixins'
import { AUTH } from '@/config/firebaseInit';
export default {
	data: () => ({
		user: {},
		profileImage: {
			width: null,
			height: null
		},
		confirmationDialog: false
	}),
	created () {
		if (this.$route.params.user !== null) {
			this.user = Object.assign({}, this.$route.params.user)
		} else {
			this.$router.push({name: 'Contacts'})
		}

		this.createFakeImage(this.user.imageObj.src)
		.then((data) => {
			this.profileImage = {
				height: data.height + 'px',
				width: data.width + 'px'
			};
		})
	},
	methods: {
		backToContacts() {
			this.$router.push({name: 'Contacts'})
		},
		viewBasket () {
			this.$router.push({name: 'ViewOfflineBasket', params: {basket: this.user}})
		},
		deleteContact () {
			const offlineContacts = JSON.parse(localStorage.getItem(`${AUTH.currentUser.uid}_offline_contacts`));

			const contactIndex = offlineContacts.findIndex(contact => contact.id === this.user.id);

			if (contactIndex !== -1) {

				offlineContacts.splice(contactIndex, 1);

				localStorage.setItem(`${AUTH.currentUser.uid}_offline_contacts`, JSON.stringify(offlineContacts));

				this.$store.dispatch('contacts/UPDATE_OFFLINE_CONTACTS_IN_CLOUD', offlineContacts)
				.then(() => {
					console.log('success')
				});

			}
		}
	},
	filters: {
		birthdayFormat (val) {
			if (!val) return '';
			return moment(val).format('MMMM DD, YYYY')
		},
		memberSince(val) {
			return moment(val).format("MMMM D")
		}
	},
	mixins: [mixins]
}

</script>

<style scoped>
.header-text {
  font-size: 11px;
}

.flipped {
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
}
</style>

