module.exports = {
  NODE_ENV: '"production"',
  apiKey: '"AIzaSyCeGcbnkddmwFtTKmNafcoXpUU1nE7Cr1I"',
  authDomain: '"ever-bilena.firebaseapp.com"',
  databaseURL: '"https://ever-bilena.firebaseio.com"',
  projectId: '"ever-bilena"',
  storageBucket: '"ever-bilena.appspot.com"',
  messagingSenderId: '"291939986733"',
  appId: '"1:291939986733:web:82beda3f7ba891db"',
  storageCode: '"ever-bilena"',
  webAdminId: '"admin"',
  companyName: '"Ever Bilena"',
  version: '"0.6.5"',
  primaryColor: '"#D80072"',
}
