<template>
	<div>

		<v-toolbar app color="primary" dark>
			<v-btn icon @click="backToMain">
				<v-icon>arrow_back</v-icon>
			</v-btn>
			<v-btn icon @click="editProfile">
				<v-icon>border_color</v-icon>
			</v-btn>
			<v-spacer></v-spacer>
			<ContactsBadge/>
			<Accounts />
		</v-toolbar>

		<v-container fluid grid-list-lg>
			<ProfileHeader :hasViewProfile="false" :hasRating="false" />
			<div :class="[user.type === 'Customer' ? 'mt-3' : 'mt-4']">
				<v-layout row wrap>
					<v-flex xs4>
						<p class="grey--text header-text" v-if="user.type === 'Reseller'">Reseller ID</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.type === 'Reseller'">{{user.agentId}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Name</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.firstName}} {{user.middleInitial}} {{user.lastName}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Birthday</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.birthday | birthdayFormat}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Gender</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.gender}}</p>
					</v-flex>
					<v-flex xs4 v-if="!user.isEmailAutogenerated">
						<p class="grey--text header-text">Email</p>
					</v-flex>
					<v-flex xs8 v-if="!user.isEmailAutogenerated">
						<p class="body-1 header-text grey--text text--darken-2">{{user.email}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Contact</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2">{{user.contact}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">House Number</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.house">{{user.address.house}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Street name</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.streetName">{{user.address.streetName}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Province</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.province">{{user.address.province}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">City/Municipality</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.citymun">{{user.address.citymun}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Barangay</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.barangay">{{user.address.barangay}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Zip Code</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.address && user.address.zipCode">{{user.address.zipCode}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Facebook</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.social && user.social.facebook">{{user.social.facebook}}</p>
					</v-flex>
					<!--<v-flex xs4>
						<p class="grey--text header-text">Instagram</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.instagram && user.social.instagram">{{user.social.instagram}}</p>
					</v-flex>
					<v-flex xs4>
						<p class="grey--text header-text">Twitter</p>
					</v-flex>
					<v-flex xs8>
						<p class="body-1 header-text grey--text text--darken-2" v-if="user.social && user.social.twitter">{{user.address.twitter}}</p>
					</v-flex>-->
				</v-layout>
			</div>
		</v-container>

		<BottomNav currentTab="more"/>
	</div>
</template>

<script>
import {mapGetters} from 'vuex';
import moment from 'moment';
import ProfileHeader from '@/components/ProfileHeader';
import ContactsBadge from '@/components/ContactsBadge';
import {mixins} from '@/mixins';

export default {
	mixins: [mixins],
	components: {
		ProfileHeader, ContactsBadge
	},
	computed: {
		...mapGetters('accounts', [
			'user'
			])
	},
	methods: {
		backToMain() {
			this.$router.go(-1);
		},
		editProfile () {
			this.$router.push({name: 'EditProfile'})
		}
	},
	filters: {
		birthdayFormat (val) {
			return moment(val).format('MMMM DD, YYYY')
		}
	}
}

</script>

<style scoped>
.header-text {
  font-size: 11px;
}
</style>

